version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3001:3000"
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CONNECTION_STRING: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}"
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  indexer:
    build:
      context: ./indexer
    image: flux-index-node
    ports: 
      - "8080:8080"
    environment:
            # TODO: Fill in 
    network:
      - flux-network    
    depends_on:
      - db
  fullnode:
    image: nearprotocol/nearcore_test
    restart: unless-stopped
    network:
      - flux-network     
    ports:
      - "8000:8000"
    environment:
        # TODO: Fill in 
volumes:
    db:
networks:
  flux-network:
    driver: bridge
